
import type { Metadata } from 'next';
import Link from 'next/link';
import { BookOpen, Search, Sparkles } from 'lucide-react';
import { ArticleCard } from '@/components/article-card';
import { getAllPosts, getCategories, getFeaturedPosts } from '@/lib/posts';
import { SITE } from '@/lib/site';

export const metadata: Metadata = { title: 'Blog', description: 'Business registration, compliance, AI and business growth articles.', alternates: { canonical: `${SITE.blogUrl}/blog` }, openGraph: { title: 'BuduTech Blog', description: 'Business registration, compliance, AI and business growth articles.', url: `${SITE.blogUrl}/blog`, images: [`${SITE.mainUrl}/og-image.svg`] } };
export default function BlogHomePage() { const featured = getFeaturedPosts(); const posts = getAllPosts(); const categories = getCategories(); return <div><section className="container-page py-12 sm:py-16 lg:py-20"><div className="grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-center"><div><div className="flex flex-wrap gap-2"><span className="pill">Blog</span><span className="pill">SEO</span><span className="pill">GEO</span><span className="pill">AEO</span></div><h1 className="h1 mt-6 max-w-4xl">The BuduTech Knowledge Hub for serious founders and business owners.</h1><p className="lead mt-6 max-w-2xl">Read guides on CAC registration, compliance, business growth, AI, and more. Built to rank, explain and convert.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/blog/articles" className="btn-primary"><Sparkles className="mr-2 h-4 w-4" />Browse Articles</Link><Link href="/blog/search" className="btn-secondary"><Search className="mr-2 h-4 w-4" />Search</Link><Link href={SITE.mainUrl} className="btn-ghost">Go to Main Site</Link></div></div><div className="card-elevated p-6"><div className="small-label">Categories</div><div className="mt-4 flex flex-wrap gap-2">{categories.map(category => <Link key={category} href={`/blog/categories/${category.toLowerCase().replace(/\s+/g,'-')}`} className="pill">{category}</Link>)}</div><div className="mt-6 rounded-[20px] bg-slate-950 p-5 text-white"><div className="text-xs uppercase tracking-[0.18em] text-slate-400">What to expect</div><div className="mt-3 text-xl font-black leading-tight">Fast answers, clear structure and practical next steps.</div></div></div></div></section><section className="container-page pb-8"><div className="small-label">Featured articles</div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{featured.map(post => <ArticleCard key={post.slug} post={post} />)}</div></section><section className="container-page py-12"><div className="card p-6 sm:p-8"><div className="small-label">Latest articles</div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{posts.slice(0,9).map(post => <ArticleCard key={post.slug} post={post} />)}</div></div></section><section className="container-page pb-16"><div className="card p-6 sm:p-8"><div className="small-label">Reader journey</div><h2 className="h2 mt-2">Read, understand, then take action</h2><p className="lead mt-4 max-w-3xl">Every article should naturally point back to the main site so users can move from information to service.</p></div></section></div>; }
