
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getAllPosts, getPostBySlug, extractHeadings, markdownToHtml } from '@/lib/posts';
import { slugify } from '@/lib/slugify';
import { SITE } from '@/lib/site';
export async function generateStaticParams() { return getAllPosts().map(post => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; try { const post = getPostBySlug(slug); return { title: post.seoTitle, description: post.seoDescription, alternates: { canonical: `${SITE.blogUrl}/blog/articles/${slug}` }, openGraph: { title: post.seoTitle, description: post.seoDescription, url: `${SITE.blogUrl}/blog/articles/${slug}`, images: [`${SITE.mainUrl}/og-image.svg`] } }; } catch { return { title: 'Article not found' }; } }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; let post: ReturnType<typeof getPostBySlug>; try { post = getPostBySlug(slug); } catch { notFound(); } const headings = extractHeadings(post.content).map(h => ({ ...h, id: slugify(h.text) })); const rawHtml = await markdownToHtml(post.content); let html = rawHtml; for (const heading of headings) { html = html.replace(`<h2>${heading.text}</h2>`, `<h2 id="${heading.id}">${heading.text}</h2>`).replace(`<h3>${heading.text}</h3>`, `<h3 id="${heading.id}">${heading.text}</h3>`); } const related = getAllPosts().filter(item => item.category === post.category && item.slug !== post.slug).slice(0,3); return <div className="container-page py-12 sm:py-16"><div className="article-meta"><span className="pill">{post.category}</span><span>{post.readingTime}</span><span>Updated {post.updated}</span><span>By {post.author}</span></div><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_300px]"><article className="max-w-none"><h1 className="h1 max-w-4xl">{post.title}</h1><p className="lead mt-5 max-w-3xl">{post.excerpt}</p><div className="mt-8 rounded-[24px] border border-slate-200 bg-white p-6 prose-like"><div dangerouslySetInnerHTML={{ __html: html }} /></div><div className="mt-10 rounded-[24px] border border-budutech-100 bg-budutech-50/60 p-6"><div className="small-label">Need help?</div><h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">Move from reading to action</h2><p className="mt-3 text-sm leading-7 text-slate-700">Go to the main site to compare service packages and continue via WhatsApp.</p><div className="mt-5 flex flex-wrap gap-3"><a href={SITE.mainUrl} className="btn-primary">Main site</a><a href="/blog/articles" className="btn-secondary">More articles</a></div></div><div className="mt-10"><div className="small-label">Related articles</div><div className="mt-5 grid gap-5 md:grid-cols-3">{related.map(item => <a key={item.slug} href={`/blog/articles/${item.slug}`} className="card p-5 hover:shadow-glow"><div className="text-xs font-semibold uppercase tracking-[0.14em] text-budutech-700">{item.category}</div><div className="mt-2 font-bold text-slate-950">{item.title}</div></a>)}</div></div></article><aside className="card sticky top-24 p-5"><div className="small-label">On this page</div><div className="mt-3 grid gap-1">{headings.map(h => <a key={h.id} href={`#${h.id}`} className="table-of-contents">{h.text}</a>)}</div></aside></div></div>; }
