
import { SITE } from '@/lib/site';
export type ServicePackage = { name: 'Basic' | 'Premium'; price: string; includes: string[] };
export type Service = { slug: string; title: string; eyebrow: string; subtitle: string; summary: string; timeline: string; cta: string; keywords: string[]; benefits: string[]; packages: ServicePackage[]; faq: { q: string; a: string }[] };
export const services: Service[] = [
  { slug:'business-name-registration', title:'Business Name Registration', eyebrow:'CAC REGISTRATION', subtitle:'Fast, simple and practical for entrepreneurs and small businesses.', summary:'Business name registration is the simplest CAC structure for founders who want to formalise their business quickly and build trust.', timeline:'Within 24 hours after Name Reservation Approval', cta:SITE.mainUrl, keywords:['CAC','business name','Nigeria','registration'], benefits:['Simple structure for solo founders and small teams','Build trust with customers and partners','Formalise your brand name','A practical starting point for early-stage businesses'], packages:[{name:'Basic',price:'₦34,999',includes:['Business Name Registration','CAC Certificate of Registration','Certified Status Report','Tax Identification Number (TIN)','Business Grants Alert Access']},{name:'Premium',price:'₦45,000',includes:['Everything in Basic','Google Business Profile Setup & Optimization','Professional Business Letterhead Design']}], faq:[{q:'Can I register from anywhere in Nigeria?',a:'Yes. The process can be handled remotely with the right support.'},{q:'Is a business name the same as a limited company?',a:'No. They are different structures.'},{q:'What if my preferred name is not available?',a:'You can choose another suitable name and continue the process.'}] },
  { slug:'limited-liability-company-registration', title:'Limited Liability Company Registration', eyebrow:'COMPANY FORMATION', subtitle:'A more formal structure for founders who want stronger corporate positioning.', summary:'A limited liability company is a better fit when you want a more formal corporate structure, stronger identity and a path for growth.', timeline:'Within 48 hours', cta:SITE.mainUrl, keywords:['company','corporate','MEMART','Nigeria'], benefits:['Stronger corporate image','Better fit for growth-focused businesses','Clear ownership structure','Useful for partnerships and scaling'], packages:[{name:'Basic',price:'₦65,000',includes:['Certificate of Incorporation','Certified Status Report','Memorandum & Articles of Association (MEMART)','Tax Identification Number (TIN)','Business Grants Alert Access']},{name:'Premium',price:'₦84,999',includes:['Everything in Basic','Google Business Profile Setup & Optimization','Professional Business Letterhead Design']}], faq:[{q:'Is company registration always better?',a:'No. It depends on your goals and the level of structure you need.'},{q:'Does it usually take longer?',a:'Yes, because it is a more detailed structure.'}] },
  { slug:'ngo-church-association-registration', title:'NGO / Church / Association Registration', eyebrow:'INCORPORATED TRUSTEES', subtitle:'For organisations that need a formal non-profit or community structure.', summary:'This structure is used for NGOs, churches, associations, foundations and community organisations that require incorporated trustees registration.', timeline:'30–90 working days', cta:SITE.mainUrl, keywords:['NGO','church','association','trustees','Nigeria'], benefits:['Suitable for non-profit and community organisations','Formal legal identity for the organisation','Structured governance path','Better presentation for compliance'], packages:[{name:'Basic',price:'₦130,000',includes:['Name Availability Search','CAC Registration Processing','Certificate of Incorporation','Certified Constitution','Certified Trustees Documentation','Registration Guidance','Tax Identification Number','Newspaper Publication']},{name:'Premium',price:'₦180,000',includes:['Everything in Basic','Professional NGO Letterhead Design','Google Business Profile Setup (where applicable)','Basic Digital Presence Consultation','SCUML Certificate']}], faq:[{q:'Can a church register this way?',a:'Yes, where appropriate.'},{q:'Why does the process take longer?',a:'Because the structure is more detailed and involves more stages.'}] },
  { slug:'scuml-registration', title:'SCUML Registration', eyebrow:'COMPLIANCE', subtitle:'For regulated businesses and organisations that need compliance support.', summary:'SCUML registration matters for businesses and organisations that fall within the applicable compliance requirements.', timeline:'Depends on the business type', cta:SITE.mainUrl, keywords:['SCUML','compliance','Nigeria'], benefits:['Compliance support','Formalisation for regulated activities','Useful for businesses in covered sectors'], packages:[{name:'Basic',price:'Custom quote',includes:['Requirements review','Document guidance','Compliance assistance']},{name:'Premium',price:'Custom quote',includes:['Everything in Basic','Extended support','Additional documentation guidance']}], faq:[{q:'Does every business need SCUML?',a:'No. It depends on the business type and the applicable requirements.'}] },
  { slug:'annual-returns', title:'Annual Returns', eyebrow:'POST-INCORPORATION', subtitle:'Keep your business active and compliant after registration.', summary:'Annual returns help you keep your registered business or company in good standing after incorporation.', timeline:'Case dependent', cta:SITE.mainUrl, keywords:['annual returns','compliance','Nigeria'], benefits:['Stay compliant','Avoid unnecessary problems later','Maintain your company record'], packages:[{name:'Basic',price:'Custom quote',includes:['Returns review','Filing guidance','Compliance support']},{name:'Premium',price:'Custom quote',includes:['Everything in Basic','Priority handling','Extended compliance support']}], faq:[{q:'Do I need annual returns after registration?',a:'Yes, where applicable to your entity type.'}] },
  { slug:'uk-company-registration', title:'UK Company Registration', eyebrow:'INTERNATIONAL', subtitle:'Structured support for founders who want a UK presence.', summary:'A UK company can be useful for founders who need a formal international presence for business, payments or credibility.', timeline:'Case dependent', cta:SITE.mainUrl, keywords:['UK company','international','formation'], benefits:['International positioning','Professional presence','Useful for cross-border business'], packages:[{name:'Basic',price:'Custom quote',includes:['Guidance','Document support']},{name:'Premium',price:'Custom quote',includes:['Everything in Basic','Extended support']}], faq:[{q:'Can I register from Nigeria?',a:'Yes, depending on the structure and support path used.'}] },
  { slug:'us-llc-registration', title:'US LLC Registration', eyebrow:'INTERNATIONAL', subtitle:'A practical route for founders seeking a US business structure.', summary:'A US LLC can suit founders who want a strong international business identity for operations, payments or expansion.', timeline:'Case dependent', cta:SITE.mainUrl, keywords:['US LLC','international','formation'], benefits:['Useful for global business positioning','Cross-border credibility','Flexible structure'], packages:[{name:'Basic',price:'Custom quote',includes:['Guidance','Document support']},{name:'Premium',price:'Custom quote',includes:['Everything in Basic','Priority handling']}], faq:[{q:'Who is this for?',a:'Founders who want a US business presence for legitimate business reasons.'}] }
];
export const getServiceBySlug = (slug: string) => services.find(s => s.slug === slug);
export const getServiceSlugs = () => services.map(s => ({ slug: s.slug }));
